// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: recruiter/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSubmitJob struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Title        string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description  string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags         string `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"`
	PostDeadline string `protobuf:"bytes,5,opt,name=postDeadline,proto3" json:"postDeadline,omitempty"`
	JobDeadline  string `protobuf:"bytes,6,opt,name=jobDeadline,proto3" json:"jobDeadline,omitempty"`
	MaxPrice     string `protobuf:"bytes,7,opt,name=maxPrice,proto3" json:"maxPrice,omitempty"`
	Location     string `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	Jobtype      uint64 `protobuf:"varint,9,opt,name=jobtype,proto3" json:"jobtype,omitempty"`
}

func (m *MsgSubmitJob) Reset()         { *m = MsgSubmitJob{} }
func (m *MsgSubmitJob) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitJob) ProtoMessage()    {}
func (*MsgSubmitJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_92c0ddfd43550e08, []int{0}
}
func (m *MsgSubmitJob) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitJob.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitJob.Merge(m, src)
}
func (m *MsgSubmitJob) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitJob) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitJob.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitJob proto.InternalMessageInfo

func (m *MsgSubmitJob) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSubmitJob) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MsgSubmitJob) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MsgSubmitJob) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *MsgSubmitJob) GetPostDeadline() string {
	if m != nil {
		return m.PostDeadline
	}
	return ""
}

func (m *MsgSubmitJob) GetJobDeadline() string {
	if m != nil {
		return m.JobDeadline
	}
	return ""
}

func (m *MsgSubmitJob) GetMaxPrice() string {
	if m != nil {
		return m.MaxPrice
	}
	return ""
}

func (m *MsgSubmitJob) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *MsgSubmitJob) GetJobtype() uint64 {
	if m != nil {
		return m.Jobtype
	}
	return 0
}

type MsgSubmitJobResponse struct {
}

func (m *MsgSubmitJobResponse) Reset()         { *m = MsgSubmitJobResponse{} }
func (m *MsgSubmitJobResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitJobResponse) ProtoMessage()    {}
func (*MsgSubmitJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92c0ddfd43550e08, []int{1}
}
func (m *MsgSubmitJobResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitJobResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitJobResponse.Merge(m, src)
}
func (m *MsgSubmitJobResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitJobResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSubmitJob)(nil), "mohammadrezatorkaman.wework.recruiter.MsgSubmitJob")
	proto.RegisterType((*MsgSubmitJobResponse)(nil), "mohammadrezatorkaman.wework.recruiter.MsgSubmitJobResponse")
}

func init() { proto.RegisterFile("recruiter/tx.proto", fileDescriptor_92c0ddfd43550e08) }

var fileDescriptor_92c0ddfd43550e08 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x3d, 0x6b, 0x32, 0x41,
	0x10, 0xc7, 0x5d, 0xdf, 0xdd, 0xc7, 0x6a, 0x91, 0x87, 0xc5, 0xe2, 0x10, 0x21, 0x60, 0x93, 0x3b,
	0x88, 0x55, 0x48, 0x17, 0x52, 0x05, 0x84, 0xa0, 0x5d, 0xba, 0xbd, 0x73, 0x38, 0x57, 0xdd, 0x9b,
	0x63, 0x77, 0x45, 0x0d, 0xa4, 0x4b, 0x99, 0x22, 0x1f, 0x2b, 0xa5, 0x65, 0xca, 0xa0, 0x5f, 0x24,
	0xdc, 0x1e, 0x67, 0x2e, 0x5d, 0x48, 0xb7, 0xff, 0xff, 0x6f, 0xde, 0x76, 0x18, 0xca, 0x34, 0x44,
	0x7a, 0x23, 0x2d, 0xe8, 0xc0, 0xee, 0xfc, 0x54, 0xa3, 0x45, 0x76, 0xa1, 0x70, 0x21, 0x94, 0x12,
	0x73, 0x0d, 0x4f, 0xc2, 0xa2, 0x5e, 0x09, 0x25, 0x12, 0x7f, 0x0b, 0x5b, 0xd4, 0x2b, 0xff, 0x1c,
	0x3f, 0x7c, 0xad, 0xd2, 0xee, 0xc4, 0xc4, 0xb3, 0x4d, 0xa8, 0xa4, 0xbd, 0xc7, 0x90, 0x71, 0xda,
	0x8a, 0x34, 0x64, 0x19, 0x9c, 0x0c, 0xc8, 0xa8, 0x33, 0x2d, 0x24, 0xeb, 0xd1, 0x86, 0x95, 0x76,
	0x0d, 0xbc, 0xea, 0xfc, 0x5c, 0xb0, 0x01, 0xfd, 0x37, 0x07, 0x13, 0x69, 0x99, 0x5a, 0x89, 0x09,
	0xaf, 0x39, 0x56, 0xb6, 0x18, 0xa3, 0x75, 0x2b, 0x62, 0xc3, 0xeb, 0x0e, 0xb9, 0x37, 0x1b, 0xd2,
	0x6e, 0x8a, 0xc6, 0xde, 0x81, 0x98, 0xaf, 0x65, 0x02, 0xbc, 0xe1, 0xd8, 0x0f, 0x2f, 0xab, 0xbc,
	0xc4, 0xf0, 0x1c, 0xd2, 0xcc, 0x2b, 0x97, 0x2c, 0xd6, 0xa7, 0x6d, 0x25, 0x76, 0x0f, 0x5a, 0x46,
	0xc0, 0x5b, 0x0e, 0x9f, 0x75, 0xc6, 0xd6, 0x18, 0x09, 0x37, 0x54, 0x3b, 0x67, 0x85, 0xce, 0xfe,
	0xb8, 0xc4, 0xd0, 0xee, 0x53, 0xe0, 0x9d, 0x01, 0x19, 0xd5, 0xa7, 0x85, 0x1c, 0xfe, 0xa7, 0xbd,
	0xf2, 0x36, 0xa6, 0x60, 0x52, 0x4c, 0x0c, 0x5c, 0xbd, 0x10, 0x5a, 0x9b, 0x98, 0x98, 0x3d, 0xd3,
	0xce, 0xf7, 0xaa, 0xc6, 0xfe, 0xaf, 0x76, 0xec, 0x97, 0x2b, 0xf6, 0x6f, 0xfe, 0x90, 0x54, 0x8c,
	0x71, 0x3b, 0x7b, 0x3f, 0x7a, 0xe4, 0x70, 0xf4, 0xc8, 0xe7, 0xd1, 0x23, 0x6f, 0x27, 0xaf, 0x72,
	0x38, 0x79, 0x95, 0x8f, 0x93, 0x57, 0x79, 0xbc, 0x8e, 0xa5, 0x5d, 0x6c, 0x42, 0x3f, 0x42, 0x15,
	0x94, 0x1b, 0x5c, 0x16, 0x1d, 0x82, 0xbc, 0x43, 0xb0, 0x0b, 0x4a, 0xc7, 0xb2, 0x4f, 0xc1, 0x84,
	0x4d, 0x77, 0x30, 0xe3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x10, 0x3e, 0x66, 0x65, 0x46, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SubmitJob(ctx context.Context, in *MsgSubmitJob, opts ...grpc.CallOption) (*MsgSubmitJobResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitJob(ctx context.Context, in *MsgSubmitJob, opts ...grpc.CallOption) (*MsgSubmitJobResponse, error) {
	out := new(MsgSubmitJobResponse)
	err := c.cc.Invoke(ctx, "/mohammadrezatorkaman.wework.recruiter.Msg/SubmitJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SubmitJob(context.Context, *MsgSubmitJob) (*MsgSubmitJobResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitJob(ctx context.Context, req *MsgSubmitJob) (*MsgSubmitJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitJob not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mohammadrezatorkaman.wework.recruiter.Msg/SubmitJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitJob(ctx, req.(*MsgSubmitJob))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mohammadrezatorkaman.wework.recruiter.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitJob",
			Handler:    _Msg_SubmitJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recruiter/tx.proto",
}

func (m *MsgSubmitJob) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitJob) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitJob) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Jobtype != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Jobtype))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Location) > 0 {
		i -= len(m.Location)
		copy(dAtA[i:], m.Location)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Location)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.MaxPrice) > 0 {
		i -= len(m.MaxPrice)
		copy(dAtA[i:], m.MaxPrice)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MaxPrice)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.JobDeadline) > 0 {
		i -= len(m.JobDeadline)
		copy(dAtA[i:], m.JobDeadline)
		i = encodeVarintTx(dAtA, i, uint64(len(m.JobDeadline)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.PostDeadline) > 0 {
		i -= len(m.PostDeadline)
		copy(dAtA[i:], m.PostDeadline)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PostDeadline)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Tags) > 0 {
		i -= len(m.Tags)
		copy(dAtA[i:], m.Tags)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Tags)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitJobResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitJobResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitJobResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSubmitJob) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Tags)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PostDeadline)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.JobDeadline)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.MaxPrice)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Location)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Jobtype != 0 {
		n += 1 + sovTx(uint64(m.Jobtype))
	}
	return n
}

func (m *MsgSubmitJobResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSubmitJob) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitJob: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitJob: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tags = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostDeadline", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PostDeadline = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobDeadline", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JobDeadline = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Location = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Jobtype", wireType)
			}
			m.Jobtype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Jobtype |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitJobResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitJobResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitJobResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
